// server/utils/gameConfig.js
module.exports = {
    // Энергия
    MAX_ENERGY: 20,
    ENERGY_RECHARGE_MINUTES: 15,

    // Рейтинг
    DEFAULT_RATING: 1000,
    RATING_CHANGE_WIN: [15, 20, 25, 30], // по стрику
    RATING_CHANGE_LOSS: 15,

    // Бой
    MAX_DEFENSE_PERCENT: 75,
    MAX_DODGE_PERCENT: 70,
    MAX_CRIT_PERCENT: 100,
    MAX_CRIT_DMG_MULTIPLIER: 4.5,
    MAX_INT_BONUS_PERCENT: 100,

    // Опыт и уровни
    BASE_EXP_MULTIPLIER: 80,
    EXP_POWER: 1.5,
    SKILL_POINTS_PER_LEVEL_LOW: 3,
    SKILL_POINTS_PER_LEVEL_HIGH: 5,
    LEVEL_BREAKPOINT: 14,

    // Кланы
    CLAN_BASE_MEMBERS: 10,
    CLAN_MEMBERS_PER_LEVEL: 5,
    CLAN_EXP_BASE: 1000,
    CLAN_EXP_POWER: 1.45,
    CLAN_LEVEL_MAX: 25,

    // Турнир
    TOURNAMENT_SIZE: 32,
    TOURNAMENT_REG_DEADLINE_HOUR: 19,
    TOURNAMENT_REG_DEADLINE_MINUTE: 50,
    TOURNAMENT_START_HOUR: 20,

    // Награды по умолчанию (бой)
    DEFAULT_COIN_REWARD_BASE: 5,
    DEFAULT_COIN_REWARD_STREAK_MULTIPLIER: [1, 1.4, 2, 4],
    DEFAULT_EXP_REWARD_BASE: 3,
    DEFAULT_EXP_REWARD_VICTORY: [10, 12, 15, 18]
};
